<?php

/**
 * @file
 * Code for the ULF Transport Request feature.
 */

include_once 'ulf_transport_request.features.inc';
include_once 'ulf_transport_request.mail.inc';
include_once 'ulf_transport_request.form_alterations.inc';

/**
 * Implements hook_menu().
 */
function ulf_transport_request_menu() {
  $items = array();

  $items['admin/config/system/transport_request/config'] = array(
    'title' => 'Transportation request',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ulf_transport_request_form_backend'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer ulf transport request settings'),
    'file' => 'ulf_transport_request.backend.inc',
    'file path' => drupal_get_path('module', 'ulf_transport_request'),
  );

  return $items;
}


/**
 * Change the entiyform after it has been inserted into db.
 * Also send mails.
 *
 * @param $entity
 * @param $entity_type
 */
function ulf_transport_request_entity_postinsert($entity, $entity_type) {
  if ($entity_type == 'entityform') {
    if ($entity->type == 'transport_request') {
      $wrapper = entity_metadata_wrapper($entity_type, $entity);
      _transport_request_notify($wrapper, 'on_submit_user');
      _transport_request_notify($wrapper, 'on_submit_admin');
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function ulf_transport_request_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'ulf_transport_request');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
